# frontend/nginx.conf

server {
  listen 80;
  root   /usr/share/nginx/html;
  index  index.html;

  location / {
    # For any request that doesn't match a file, serve index.html
    try_files $uri /index.html;
  }
}