version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: app/Dockerfile
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    networks:
      - app-network

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx-proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "4533:80" # <-- This is the only line changed
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local