version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: app/Dockerfile # Specifies the path to the Dockerfile
    restart: always
    environment:
      # We will connect to the 'mongo' service defined below
      - MONGO_URI=mongodb://mongo:27017/mydatabase 
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend # Assumes the frontend Dockerfile is in the 'frontend' folder
    restart: always
    networks:
      - app-network

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db # Persists database data on the EC2 host
    networks:
      - app-network

  nginx-proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80" # Expose port 80 to the world
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # We'll create this file next
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local